# Generated by Django 2.1.2 on 2018-12-18 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('images', models.CharField(max_length=200)),
                ('popularity', models.IntegerField()),
                ('release_date', models.CharField(max_length=11)),
                ('duration', models.FloatField()),
                ('spotid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('spotid', models.CharField(max_length=50)),
                ('genurl', models.CharField(default='unlucky', max_length=8)),
                ('tipo', models.CharField(max_length=20)),
                ('msg', models.CharField(default='just play', max_length=500)),
                ('visto', models.BooleanField(default=False)),
                ('prova', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('image', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=200)),
                ('followers', models.IntegerField()),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=50)),
                ('rtoken', models.CharField(max_length=200)),
                ('atoken', models.CharField(max_length=200)),
                ('texpiresat', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='recommend',
            name='recdado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recdado', to='spotify.Username'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='recmander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recmander', to='spotify.Username'),
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.Username'),
        ),
        migrations.AddField(
            model_name='answer',
            name='rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.Recommend'),
        ),
    ]
