# Generated by Django 2.1.2 on 2018-12-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20181218_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='recdado',
            field=models.CharField(max_length=100),
        ),
    ]
