# Generated by Django 2.1.2 on 2018-12-18 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20181218_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='recmander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.Username'),
        ),
    ]
