# Generated by Django 2.1.2 on 2018-12-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20181218_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='recdado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recdado', to='spotify.Username'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='recmander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recmander', to='spotify.Username'),
        ),
    ]
