# Generated by Django 2.1.2 on 2018-12-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_auto_20181229_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='recdado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recdado', to='spotify.Username'),
        ),
    ]
