# Generated by Django 2.1.2 on 2019-01-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_auto_20181229_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rec',
        ),
        migrations.AddField(
            model_name='recommend',
            name='ans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='spotify.Answer'),
        ),
    ]
