# Generated by Django 2.1.2 on 2019-01-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_auto_20190104_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='ans',
            new_name='answer',
        ),
    ]
