# Generated by Django 2.1.2 on 2019-01-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_auto_20190104_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='historyperm',
            field=models.BooleanField(default=False),
        ),
    ]
