# Generated by Django 2.1.2 on 2019-01-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_auto_20190104_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
