# Generated by Django 2.1.2 on 2019-01-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_recommend_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='user',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
