# Generated by Django 2.1.2 on 2019-01-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='URL',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='username',
            name='atoken',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='username',
            name='historyperm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='username',
            name='rtoken',
            field=models.CharField(max_length=500),
        ),
    ]
